name: task_wtf
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
   sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.1
  intl: ^0.17.0
  flutter_bloc: ^7.3.0
  shared_preferences: ^2.0.6
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - image/bot.png



